spring:
  application:
    name: ${APP_NAME:sso_starter}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        dialect:
          org:
            hibernate:
              dialect: ${JPA_DIALECT:MySQL8Dialect}

